[build]
    command = "yarn install && yarn build"
    publish = ".next"

[build.environment]
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    TERM = "xterm"
    NETLIFY_USE_YARN = "true"
    NODE_VERSION="18.4.0"
    NPM_FLAGS="--dry-run"

[[plugins]]
    package = "netlify-plugin-cypress"

    [plugins.inputs]
        enable = false
        
    [plugins.inputs.postBuild]
        record = true
        enable = true
        spa = true
        start = 'yarn dev -p 8080'