[build]
    command = "yarn install && yarn build"
    publish = ".next"

[build.environment]
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    TERM = "xterm"
    NETLIFY_USE_YARN = "true"
    NODE_VERSION="18.4.0"
    NPM_FLAGS="--dry-run"

[[plugins]]
    package = "netlify-plugin-cypress"

    [plugins.inputs.postBuild]
        enable = true
        start = 'yarn start'
        wait-on = 'http://localhost:3000'
        wait-on-timeout = '15' # seconds